version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - data-volume:/backend/uploads

  frontend:
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile.frontend
    ports:
      - "3000:3000"

volumes:
  data-volume:
